// src/pages/Papers.jsx
// Admin-only view: see all generated paper sets and download any as PDF.

import { useState } from "react";
import { Header, Card, Badge, Empty } from "../components/UI";

export default function Papers({ user, papers, onDelete }) {
  const [selected, setSelected] = useState(null);
  const [activeSet, setActiveSet] = useState("A");

  // Filter papers: teachers see only their papers, admins see all
  const isAdmin = user.role === "admin";
  const userPapers = isAdmin ? papers : papers.filter(p => p.generatedBy === user.username);

  const downloadPDF = (paper, setKey) => {
    const s = paper.sets[setKey];
    if (!s) return;
    const dateStr = new Date(paper.generatedAt).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });

    const renderRows = (qs) => qs.map((q, i) =>
      `<tr><td style="padding:8px 4px;color:#555;font-size:13px;vertical-align:top">${i + 1}.</td>
       <td style="padding:8px;font-size:13px;">${q.question}</td>
       <td style="padding:8px 4px;text-align:right;font-size:13px;white-space:nowrap">[${q.marks}M]</td></tr>`
    ).join("");

    const html = `<!DOCTYPE html><html><head><title>${paper.subject} Set ${setKey}</title>
<style>body{font-family:Georgia,serif;margin:0;padding:40px;color:#111}
h1{font-size:20px;text-align:center;margin:0 0 4px}
.meta{text-align:center;font-size:13px;color:#555;margin-bottom:24px}
h2{font-size:14px;border-bottom:2px solid #111;padding-bottom:4px;margin:24px 0 12px}
table{width:100%;border-collapse:collapse}
.footer{margin-top:40px;text-align:center;font-size:12px;color:#888;border-top:1px solid #ddd;padding-top:12px}
@media print{@page{margin:20mm}}</style></head>
<body>
<p style="text-align:right;font-size:12px;color:#888">CONFIDENTIAL — EXAMINER COPY</p>
<h1>${paper.subject} Examination — Set ${setKey}</h1>
<div class="meta">
  ${paper.courseId ? `<strong>${paper.courseId}</strong> &nbsp;|&nbsp;` : ""}
  Level: ${paper.level} &nbsp;|&nbsp; Total Marks: 50 &nbsp;|&nbsp; Duration: 3 Hours &nbsp;|&nbsp; Date: ${dateStr}
</div>
<h2>SECTION A — Short Answer (2 × 5 = 10 Marks)</h2>
<table>${renderRows(s.sectionA)}</table>
<h2>SECTION B — Medium Answer (5 × 4 = 20 Marks)</h2>
<table>${renderRows(s.sectionB)}</table>
<h2>SECTION C — Long Answer (10 × 2 = 20 Marks)</h2>
<table>${renderRows(s.sectionC)}</table>
<div class="footer">SecureExam AI &nbsp;|&nbsp; ${paper.subject} ${paper.courseId || ""} &nbsp;|&nbsp; Set ${setKey} &nbsp;|&nbsp; ${dateStr}</div>
</body></html>`;

    const win = window.open("", "_blank");
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  };

  const SectionPreview = ({ title, qs, col }) => (
    <div className="mb-4">
      <div className="flex items-center justify-between mb-2 pb-1.5 border-b" style={{ borderColor: "#1E2D4A" }}>
        <h4 className="text-xs font-bold" style={{ color: "#E2E8F0" }}>{title}</h4>
        <span className="text-xs" style={{ color: col }}>{qs.reduce((a, q) => a + q.marks, 0)}M</span>
      </div>
      {qs.map((q, i) => (
        <div key={i} className="flex gap-2 py-2 border-b last:border-0 text-xs" style={{ borderColor: "#141B30" }}>
          <span style={{ color: col, fontWeight: 600, shrink: 0 }}>{i + 1}.</span>
          <p className="flex-1 leading-relaxed" style={{ color: "#E2E8F0" }}>{q.question}</p>
          <span style={{ color: col, fontWeight: 600, whiteSpace: "nowrap" }}>[{q.marks}M]</span>
        </div>
      ))}
    </div>
  );

  return (
    <div>
      <Header title="Generated Papers" subtitle={isAdmin ? "All question papers generated by teachers" : "Your generated question papers — download or delete"} />

      {userPapers.length === 0 ? (
        <Card>
          <Empty message={isAdmin ? "No papers generated yet. Teachers generate papers from the Generate Paper section." : "No papers generated yet. Generate papers from the Generate Paper section."} />
        </Card>
      ) : (
        <div className="space-y-3">
          {userPapers.map((paper, idx) => (
            <Card key={idx}>
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <p className="text-sm font-semibold" style={{ color: "#E2E8F0" }}>{paper.subject}</p>
                  <p className="text-xs mt-0.5" style={{ color: "#64748B" }}>
                    {paper.courseId && <span style={{ color: "#3B82F6", fontFamily: "monospace" }}>{paper.courseId} · </span>}
                    {paper.level} · by <span style={{ color: "#E2E8F0" }}>{paper.generatedBy}</span>
                    {" · "}{new Date(paper.generatedAt).toLocaleString()}
                  </p>
                  {paper.template && (
                    <p className="text-xs mt-0.5" style={{ color: "#475569" }}>Template: {paper.template}</p>
                  )}
                </div>
                <Badge color="green">3 Sets</Badge>
              </div>

              {/* Expand/collapse + delete */}
              <div className="mt-3 flex gap-2 flex-wrap">
                <button
                  onClick={() => setSelected(selected === idx ? null : idx)}
                  className="px-3 py-1.5 rounded text-xs font-medium"
                  style={{ background: selected === idx ? "#1A2340" : "#141B30", color: "#3B82F6", border: "1px solid #1E2D4A" }}>
                  {selected === idx ? "▲ Hide Preview" : "▼ Preview Paper"}
                </button>
                {["A", "B", "C"].map(s => (
                  <button key={s} onClick={() => downloadPDF(paper, s)}
                    className="px-3 py-1.5 rounded text-xs font-semibold"
                    style={{ background: "#059669", color: "white" }}>
                    ⬇ Set {s} PDF
                  </button>
                ))}
                {!isAdmin && (
                  <button
                    onClick={() => {
                      if (window.confirm("Are you sure you want to delete this paper? This cannot be undone.")) {
                        onDelete(paper.id);
                      }
                    }}
                    className="px-3 py-1.5 rounded text-xs font-semibold ml-auto"
                    style={{ background: "#DC2626", color: "white" }}>
                    🗑 Delete
                  </button>
                )}
              </div>

              {/* Expanded preview */}
              {selected === idx && (
                <div className="mt-4 pt-4 border-t" style={{ borderColor: "#1E2D4A" }}>
                  <div className="flex gap-2 mb-4">
                    {["A", "B", "C"].map(s => (
                      <button key={s} onClick={() => setActiveSet(s)}
                        className="flex-1 py-2 rounded-lg text-xs font-bold"
                        style={{
                          background: activeSet === s ? "linear-gradient(135deg,#1D4ED8,#3B82F6)" : "#141B30",
                          color: activeSet === s ? "white" : "#64748B",
                          border: `1px solid ${activeSet === s ? "#3B82F6" : "#1E2D4A"}`,
                        }}>
                        Set {s}
                      </button>
                    ))}
                  </div>

                  <div className="text-center mb-4 py-3 rounded-lg" style={{ background: "#141B30" }}>
                    <p className="text-sm font-bold" style={{ color: "#E2E8F0" }}>
                      {paper.subject} — Set {activeSet}
                    </p>
                    <p className="text-xs mt-0.5" style={{ color: "#64748B" }}>
                      {paper.courseId} · 50 Marks · 3 Hours
                    </p>
                  </div>

                  {paper.sets[activeSet] && (
                    <>
                      <SectionPreview title="SECTION A — Short Answer (2M each)" qs={paper.sets[activeSet].sectionA} col="#3B82F6" />
                      <SectionPreview title="SECTION B — Medium Answer (5M each)" qs={paper.sets[activeSet].sectionB} col="#F59E0B" />
                      <SectionPreview title="SECTION C — Long Answer (10M each)"  qs={paper.sets[activeSet].sectionC} col="#EF4444" />
                    </>
                  )}
                </div>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
